#include "MCPTools/MCPEdGraphTools.h"
#include "MCPTools/UnrealMCPCommonUtils.h"
#include "EdGraph/EdGraph.h"
#include "EdGraph/EdGraphNode.h"
#include "EdGraphNode_Comment.h"
#include "EdGraph/EdGraphPin.h"
#include "EdGraph/EdGraphSchema.h"
#include "EditorAssetLibrary.h"
#include "Engine/Blueprint.h"
#include "Engine/SimpleConstructionScript.h"
#include "Engine/SCS_Node.h"
#include "EdGraphSchema_K2.h"
#include "Kismet2/BlueprintEditorUtils.h"
#include "Kismet2/KismetEditorUtilities.h"
#include "Logging/MessageLog.h"
#include "Dom/JsonObject.h"
#include "UObject/UObjectIterator.h"
#include "UObject/PropertyIterator.h"

// ─────────────────── Private helpers ───────────────────

UEdGraphNode* UMCPEdGraphTools::FindNodeInGraph(UEdGraph* Graph, const FString& NodeGuid, const FString& NodeName, const FString& NodePath)
{
	if (!Graph)
	{
		return nullptr;
	}

	if (!NodePath.IsEmpty())
	{
		UEdGraphNode* Node = LoadObject<UEdGraphNode>(nullptr, *NodePath);
		if (Node)
		{
			return Node;
		}
	}

	for (UEdGraphNode* Node : Graph->Nodes)
	{
		if (!Node)
		{
			continue;
		}
		if (!NodeGuid.IsEmpty() && Node->NodeGuid.ToString() == NodeGuid)
		{
			return Node;
		}
		if (!NodeName.IsEmpty() && Node->GetName() == NodeName)
		{
			return Node;
		}
	}
	return nullptr;
}

TSharedPtr<FJsonObject> UMCPEdGraphTools::SerializePin(UEdGraphPin* Pin)
{
	TSharedPtr<FJsonObject> PinObj = MakeShared<FJsonObject>();
	if (!Pin)
	{
		return PinObj;
	}
	PinObj->SetStringField(TEXT("name"), Pin->PinName.ToString());
	PinObj->SetStringField(TEXT("direction"), (Pin->Direction == EGPD_Input) ? TEXT("Input") : TEXT("Output"));
	PinObj->SetStringField(TEXT("type"), Pin->PinType.PinCategory.ToString());

	if (!Pin->PinType.PinSubCategory.IsNone())
	{
		PinObj->SetStringField(TEXT("sub_category"), Pin->PinType.PinSubCategory.ToString());
	}
	if (Pin->PinType.PinSubCategoryObject.IsValid())
	{
		PinObj->SetStringField(TEXT("sub_category_object"), Pin->PinType.PinSubCategoryObject->GetPathName());
	}

	PinObj->SetBoolField(TEXT("is_array"), Pin->PinType.IsArray());
	PinObj->SetBoolField(TEXT("is_set"), Pin->PinType.IsSet());
	PinObj->SetBoolField(TEXT("is_map"), Pin->PinType.IsMap());
	PinObj->SetBoolField(TEXT("is_reference"), Pin->PinType.bIsReference);
	PinObj->SetBoolField(TEXT("is_const"), Pin->PinType.bIsConst);

	if (!Pin->DefaultValue.IsEmpty())
	{
		PinObj->SetStringField(TEXT("default_value"), Pin->DefaultValue);
	}
	if (Pin->DefaultObject)
	{
		PinObj->SetStringField(TEXT("default_object"), Pin->DefaultObject->GetPathName());
	}
	if (!Pin->AutogeneratedDefaultValue.IsEmpty())
	{
		PinObj->SetStringField(TEXT("auto_generated_default_value"), Pin->AutogeneratedDefaultValue);
	}

	PinObj->SetNumberField(TEXT("linked_to_count"), Pin->LinkedTo.Num());
	if (Pin->LinkedTo.Num() > 0)
	{
		TArray<TSharedPtr<FJsonValue>> LinkedArray;
		for (UEdGraphPin* LinkedPin : Pin->LinkedTo)
		{
			if (!LinkedPin || !LinkedPin->GetOwningNode())
			{
				continue;
			}
			TSharedPtr<FJsonObject> LinkObj = MakeShared<FJsonObject>();
			LinkObj->SetStringField(TEXT("node_guid"), LinkedPin->GetOwningNode()->NodeGuid.ToString());
			LinkObj->SetStringField(TEXT("node_name"), LinkedPin->GetOwningNode()->GetName());
			LinkObj->SetStringField(TEXT("pin_name"), LinkedPin->PinName.ToString());
			LinkedArray.Add(MakeShared<FJsonValueObject>(LinkObj));
		}
		PinObj->SetArrayField(TEXT("linked_to"), LinkedArray);
	}

	return PinObj;
}

TSharedPtr<FJsonObject> UMCPEdGraphTools::SerializeNode(UEdGraphNode* Node, bool bIncludeProperties)
{
	TSharedPtr<FJsonObject> NodeObj = MakeShared<FJsonObject>();
	if (!Node)
	{
		return NodeObj;
	}

	NodeObj->SetStringField(TEXT("name"), Node->GetName());
	NodeObj->SetStringField(TEXT("path"), Node->GetPathName());
	NodeObj->SetStringField(TEXT("class"), Node->GetClass() ? Node->GetClass()->GetName() : TEXT(""));
	NodeObj->SetStringField(TEXT("guid"), Node->NodeGuid.ToString());
	NodeObj->SetNumberField(TEXT("pos_x"), Node->NodePosX);
	NodeObj->SetNumberField(TEXT("pos_y"), Node->NodePosY);

	FString Title = Node->GetNodeTitle(ENodeTitleType::FullTitle).ToString();
	if (!Title.IsEmpty())
	{
		NodeObj->SetStringField(TEXT("title"), Title);
	}

	FString Comment = Node->NodeComment;
	if (!Comment.IsEmpty())
	{
		NodeObj->SetStringField(TEXT("comment"), Comment);
	}

	TArray<TSharedPtr<FJsonValue>> PinsArray;
	for (UEdGraphPin* Pin : Node->Pins)
	{
		if (!Pin)
		{
			continue;
		}
		PinsArray.Add(MakeShared<FJsonValueObject>(SerializePin(Pin)));
	}
	NodeObj->SetArrayField(TEXT("pins"), PinsArray);

	if (bIncludeProperties)
	{
		TSharedPtr<FJsonObject> PropertiesObj = MakeShared<FJsonObject>();
		UClass* NodeClass = Node->GetClass();
		UClass* StopAtClass = UEdGraphNode::StaticClass();

		for (TFieldIterator<FProperty> PropIt(NodeClass); PropIt; ++PropIt)
		{
			FProperty* Prop = *PropIt;
			if (!Prop) continue;

			// Skip properties inherited from UEdGraphNode base (position, guid, pins, etc. are already serialized above)
			if (Prop->GetOwnerClass() == StopAtClass || Prop->GetOwnerClass() == UObject::StaticClass())
			{
				continue;
			}

			// Skip deprecated and transient properties
			if (Prop->HasAnyPropertyFlags(CPF_Deprecated | CPF_Transient))
			{
				continue;
			}

			FString ExportedText;
			const void* ValuePtr = Prop->ContainerPtrToValuePtr<void>(Node);
			Prop->ExportText_Direct(ExportedText, ValuePtr, nullptr, Node, PPF_None);

			TSharedPtr<FJsonObject> PropObj = MakeShared<FJsonObject>();
			PropObj->SetStringField(TEXT("type"), Prop->GetCPPType());
			PropObj->SetStringField(TEXT("export_text"), ExportedText);
			PropertiesObj->SetObjectField(Prop->GetName(), PropObj);
		}
		NodeObj->SetObjectField(TEXT("properties"), PropertiesObj);
	}

	return NodeObj;
}

UEdGraphPin* UMCPEdGraphTools::FindPinOnNode(UEdGraphNode* Node, const FString& PinName, const FString& Direction)
{
	if (!Node || PinName.IsEmpty())
	{
		return nullptr;
	}
	for (UEdGraphPin* Pin : Node->Pins)
	{
		if (!Pin)
		{
			continue;
		}
		if (Pin->PinName.ToString() != PinName)
		{
			continue;
		}
		if (!Direction.IsEmpty())
		{
			bool bIsInput = (Pin->Direction == EGPD_Input);
			if (Direction.Equals(TEXT("Input"), ESearchCase::IgnoreCase) && !bIsInput)
			{
				continue;
			}
			if (Direction.Equals(TEXT("Output"), ESearchCase::IgnoreCase) && bIsInput)
			{
				continue;
			}
		}
		return Pin;
	}
	return nullptr;
}

bool UMCPEdGraphTools::SaveAssetIfNeeded(const FString& AssetPath)
{
	if (AssetPath.IsEmpty())
	{
		return false;
	}
	return UEditorAssetLibrary::SaveAsset(AssetPath, false);
}

// ─────────────────── HandleFindGraphsInAsset ───────────────────

FJsonObjectParameter UMCPEdGraphTools::HandleFindGraphsInAsset(const FJsonObjectParameter& Params)
{
	FString AssetPath;
	if (!Params->TryGetStringField(TEXT("asset_path"), AssetPath))
	{
		return FUnrealMCPCommonUtils::CreateErrorResponse(TEXT("Missing 'asset_path' parameter"));
	}

	FString NameFilter;
	Params->TryGetStringField(TEXT("name_filter"), NameFilter);

	double DMaxResults = 50.0;
	Params->TryGetNumberField(TEXT("max_results"), DMaxResults);
	int32 MaxResults = FMath::Clamp(static_cast<int32>(DMaxResults), 1, 200);

	UObject* Asset = LoadObject<UObject>(nullptr, *AssetPath);
	if (!Asset)
	{
		Asset = UEditorAssetLibrary::LoadAsset(AssetPath);
	}
	if (!Asset)
	{
		return FUnrealMCPCommonUtils::CreateErrorResponse(FString::Printf(TEXT("Asset not found: %s"), *AssetPath));
	}

	TArray<UEdGraph*> Graphs;

	// Blueprint-specific: use FBlueprintEditorUtils
	UBlueprint* BP = Cast<UBlueprint>(Asset);
	if (BP)
	{
		for (UEdGraph* Graph : BP->UbergraphPages)
		{
			if (Graph)
			{
				Graphs.AddUnique(Graph);
			}
		}
		for (UEdGraph* Graph : BP->FunctionGraphs)
		{
			if (Graph)
			{
				Graphs.AddUnique(Graph);
			}
		}
		for (UEdGraph* Graph : BP->MacroGraphs)
		{
			if (Graph)
			{
				Graphs.AddUnique(Graph);
			}
		}
		for (UEdGraph* Graph : BP->DelegateSignatureGraphs)
		{
			if (Graph)
			{
				Graphs.AddUnique(Graph);
			}
		}
		for (UEdGraph* Graph : BP->EventGraphs)
		{
			if (Graph)
			{
				Graphs.AddUnique(Graph);
			}
		}
	}

	// Generic: scan sub-objects for EdGraph instances
	TArray<UObject*> SubObjects;
	GetObjectsWithOuter(Asset, SubObjects, false);
	for (UObject* Obj : SubObjects)
	{
		UEdGraph* Graph = Cast<UEdGraph>(Obj);
		if (Graph)
		{
			Graphs.AddUnique(Graph);
		}
	}

	// Build result
	TArray<TSharedPtr<FJsonValue>> GraphsArray;
	for (UEdGraph* Graph : Graphs)
	{
		if (GraphsArray.Num() >= MaxResults)
		{
			break;
		}
		if (!Graph)
		{
			continue;
		}

		FString GraphPath = Graph->GetPathName();
		if (!NameFilter.IsEmpty() && !GraphPath.Contains(NameFilter))
		{
			continue;
		}

		TSharedPtr<FJsonObject> GraphObj = MakeShared<FJsonObject>();
		GraphObj->SetStringField(TEXT("name"), Graph->GetName());
		GraphObj->SetStringField(TEXT("path"), GraphPath);
		GraphObj->SetStringField(TEXT("class"), Graph->GetClass() ? Graph->GetClass()->GetName() : TEXT(""));
		GraphObj->SetNumberField(TEXT("node_count"), Graph->Nodes.Num());
		GraphsArray.Add(MakeShared<FJsonValueObject>(GraphObj));
	}

	TSharedPtr<FJsonObject> ResultObj = MakeShared<FJsonObject>();
	ResultObj->SetStringField(TEXT("asset_path"), AssetPath);
	ResultObj->SetStringField(TEXT("asset_class"), Asset->GetClass() ? Asset->GetClass()->GetName() : TEXT(""));
	ResultObj->SetNumberField(TEXT("graph_count"), GraphsArray.Num());
	ResultObj->SetArrayField(TEXT("graphs"), GraphsArray);
	return FUnrealMCPCommonUtils::CreateSuccessResponse(ResultObj);
}

// ─────────────────── HandleListGraphNodes ───────────────────

FJsonObjectParameter UMCPEdGraphTools::HandleListGraphNodes(const FJsonObjectParameter& Params)
{
	FString GraphPath;
	if (!Params->TryGetStringField(TEXT("graph_path"), GraphPath))
	{
		return FUnrealMCPCommonUtils::CreateErrorResponse(TEXT("Missing 'graph_path' parameter"));
	}

	bool bIncludeProperties = false;
	Params->TryGetBoolField(TEXT("include_properties"), bIncludeProperties);

	UEdGraph* Graph = LoadObject<UEdGraph>(nullptr, *GraphPath);
	if (!Graph)
	{
		return FUnrealMCPCommonUtils::CreateErrorResponse(FString::Printf(TEXT("Graph not found: %s"), *GraphPath));
	}

	TArray<TSharedPtr<FJsonValue>> NodesArray;
	for (UEdGraphNode* Node : Graph->Nodes)
	{
		if (!Node)
		{
			continue;
		}
		NodesArray.Add(MakeShared<FJsonValueObject>(SerializeNode(Node, bIncludeProperties)));
	}

	TSharedPtr<FJsonObject> ResultObj = MakeShared<FJsonObject>();
	ResultObj->SetStringField(TEXT("graph_path"), Graph->GetPathName());
	ResultObj->SetStringField(TEXT("graph_name"), Graph->GetName());
	ResultObj->SetStringField(TEXT("graph_class"), Graph->GetClass() ? Graph->GetClass()->GetName() : TEXT(""));
	ResultObj->SetNumberField(TEXT("node_count"), Graph->Nodes.Num());
	ResultObj->SetArrayField(TEXT("nodes"), NodesArray);
	return FUnrealMCPCommonUtils::CreateSuccessResponse(ResultObj);
}

// ─────────────────── HandleGetGraphNode ───────────────────

FJsonObjectParameter UMCPEdGraphTools::HandleGetGraphNode(const FJsonObjectParameter& Params)
{
	FString GraphPath;
	if (!Params->TryGetStringField(TEXT("graph_path"), GraphPath))
	{
		return FUnrealMCPCommonUtils::CreateErrorResponse(TEXT("Missing 'graph_path' parameter"));
	}

	FString NodeGuid, NodeName, NodePath;
	Params->TryGetStringField(TEXT("node_guid"), NodeGuid);
	Params->TryGetStringField(TEXT("node_name"), NodeName);
	Params->TryGetStringField(TEXT("node_path"), NodePath);

	UEdGraph* Graph = LoadObject<UEdGraph>(nullptr, *GraphPath);
	if (!Graph)
	{
		return FUnrealMCPCommonUtils::CreateErrorResponse(FString::Printf(TEXT("Graph not found: %s"), *GraphPath));
	}

	UEdGraphNode* Node = FindNodeInGraph(Graph, NodeGuid, NodeName, NodePath);
	if (!Node)
	{
		return FUnrealMCPCommonUtils::CreateErrorResponse(TEXT("Node not found"));
	}

	TSharedPtr<FJsonObject> ResultObj = MakeShared<FJsonObject>();
	ResultObj->SetObjectField(TEXT("node"), SerializeNode(Node, true));
	return FUnrealMCPCommonUtils::CreateSuccessResponse(ResultObj);
}

// ─────────────────── HandleDeleteGraphNode ───────────────────

FJsonObjectParameter UMCPEdGraphTools::HandleDeleteGraphNode(const FJsonObjectParameter& Params)
{
	FString GraphPath;
	if (!Params->TryGetStringField(TEXT("graph_path"), GraphPath))
	{
		return FUnrealMCPCommonUtils::CreateErrorResponse(TEXT("Missing 'graph_path' parameter"));
	}

	FString NodeGuid, NodeName, NodePath;
	Params->TryGetStringField(TEXT("node_guid"), NodeGuid);
	Params->TryGetStringField(TEXT("node_name"), NodeName);
	Params->TryGetStringField(TEXT("node_path"), NodePath);

	FString AutoSavePath;
	Params->TryGetStringField(TEXT("auto_save_asset_path"), AutoSavePath);

	UEdGraph* Graph = LoadObject<UEdGraph>(nullptr, *GraphPath);
	if (!Graph)
	{
		return FUnrealMCPCommonUtils::CreateErrorResponse(FString::Printf(TEXT("Graph not found: %s"), *GraphPath));
	}

	UEdGraphNode* Node = FindNodeInGraph(Graph, NodeGuid, NodeName, NodePath);
	if (!Node)
	{
		return FUnrealMCPCommonUtils::CreateErrorResponse(TEXT("Node not found"));
	}

	FString RemovedNodePath = Node->GetPathName();
	Graph->Modify();

	// Break all pin links first
	Node->BreakAllNodeLinks();
	Graph->RemoveNode(Node);

	if (!AutoSavePath.IsEmpty())
	{
		SaveAssetIfNeeded(AutoSavePath);
	}

	TSharedPtr<FJsonObject> ResultObj = MakeShared<FJsonObject>();
	ResultObj->SetStringField(TEXT("removed_node"), RemovedNodePath);
	return FUnrealMCPCommonUtils::CreateSuccessResponse(ResultObj);
}

// ─────────────────── HandleSetNodeProperties ───────────────────

FJsonObjectParameter UMCPEdGraphTools::HandleSetNodeProperties(const FJsonObjectParameter& Params)
{
	FString GraphPath;
	if (!Params->TryGetStringField(TEXT("graph_path"), GraphPath))
	{
		return FUnrealMCPCommonUtils::CreateErrorResponse(TEXT("Missing 'graph_path' parameter"));
	}

	FString NodeGuid, NodeName, NodePath;
	Params->TryGetStringField(TEXT("node_guid"), NodeGuid);
	Params->TryGetStringField(TEXT("node_name"), NodeName);
	Params->TryGetStringField(TEXT("node_path"), NodePath);

	const TSharedPtr<FJsonObject>* PropertiesPtr = nullptr;
	if (!Params->TryGetObjectField(TEXT("properties"), PropertiesPtr) || !PropertiesPtr || !PropertiesPtr->IsValid())
	{
		return FUnrealMCPCommonUtils::CreateErrorResponse(TEXT("Missing or invalid 'properties' parameter"));
	}

	FString AutoSavePath;
	Params->TryGetStringField(TEXT("auto_save_asset_path"), AutoSavePath);

	UEdGraph* Graph = LoadObject<UEdGraph>(nullptr, *GraphPath);
	if (!Graph)
	{
		return FUnrealMCPCommonUtils::CreateErrorResponse(FString::Printf(TEXT("Graph not found: %s"), *GraphPath));
	}

	UEdGraphNode* Node = FindNodeInGraph(Graph, NodeGuid, NodeName, NodePath);
	if (!Node)
	{
		return FUnrealMCPCommonUtils::CreateErrorResponse(TEXT("Node not found"));
	}

	Node->Modify();

	TSharedPtr<FJsonObject> AppliedObj = MakeShared<FJsonObject>();
	TSharedPtr<FJsonObject> ErrorsObj = MakeShared<FJsonObject>();

	for (const auto& Pair : (*PropertiesPtr)->Values)
	{
		FString ErrorMessage;
		bool bOk = FUnrealMCPCommonUtils::SetObjectProperty(Node, Pair.Key, Pair.Value, ErrorMessage);
		if (bOk)
		{
			AppliedObj->SetField(Pair.Key, Pair.Value);
		}
		else
		{
			ErrorsObj->SetStringField(Pair.Key, ErrorMessage);
		}
	}

	if (!AutoSavePath.IsEmpty())
	{
		SaveAssetIfNeeded(AutoSavePath);
	}

	TSharedPtr<FJsonObject> ResultObj = MakeShared<FJsonObject>();
	ResultObj->SetObjectField(TEXT("node"), SerializeNode(Node, false));
	ResultObj->SetObjectField(TEXT("applied"), AppliedObj);
	ResultObj->SetObjectField(TEXT("errors"), ErrorsObj);
	return FUnrealMCPCommonUtils::CreateSuccessResponse(ResultObj);
}

// ─────────────────── HandleListGraphLinks ───────────────────

FJsonObjectParameter UMCPEdGraphTools::HandleListGraphLinks(const FJsonObjectParameter& Params)
{
	FString GraphPath;
	if (!Params->TryGetStringField(TEXT("graph_path"), GraphPath))
	{
		return FUnrealMCPCommonUtils::CreateErrorResponse(TEXT("Missing 'graph_path' parameter"));
	}

	UEdGraph* Graph = LoadObject<UEdGraph>(nullptr, *GraphPath);
	if (!Graph)
	{
		return FUnrealMCPCommonUtils::CreateErrorResponse(FString::Printf(TEXT("Graph not found: %s"), *GraphPath));
	}

	TSet<FString> Seen;
	TArray<TSharedPtr<FJsonValue>> LinksArray;

	for (UEdGraphNode* Node : Graph->Nodes)
	{
		if (!Node)
		{
			continue;
		}
		FString NodeGuid = Node->NodeGuid.ToString();

		for (UEdGraphPin* Pin : Node->Pins)
		{
			if (!Pin)
			{
				continue;
			}
			FString PinName = Pin->PinName.ToString();

			for (UEdGraphPin* LinkedPin : Pin->LinkedTo)
			{
				if (!LinkedPin || !LinkedPin->GetOwningNode())
				{
					continue;
				}
				FString OtherGuid = LinkedPin->GetOwningNode()->NodeGuid.ToString();
				FString OtherPinName = LinkedPin->PinName.ToString();

				// Deduplicate (unordered pair)
				FString KeyA = FString::Printf(TEXT("%s:%s"), *NodeGuid, *PinName);
				FString KeyB = FString::Printf(TEXT("%s:%s"), *OtherGuid, *OtherPinName);
				FString Key = (KeyA < KeyB)
					? FString::Printf(TEXT("%s|%s"), *KeyA, *KeyB)
					: FString::Printf(TEXT("%s|%s"), *KeyB, *KeyA);
				if (Seen.Contains(Key))
				{
					continue;
				}
				Seen.Add(Key);

				TSharedPtr<FJsonObject> AObj = MakeShared<FJsonObject>();
				AObj->SetStringField(TEXT("node_guid"), NodeGuid);
				AObj->SetStringField(TEXT("node_name"), Node->GetName());
				AObj->SetStringField(TEXT("pin"), PinName);

				TSharedPtr<FJsonObject> BObj = MakeShared<FJsonObject>();
				BObj->SetStringField(TEXT("node_guid"), OtherGuid);
				BObj->SetStringField(TEXT("node_name"), LinkedPin->GetOwningNode()->GetName());
				BObj->SetStringField(TEXT("pin"), OtherPinName);

				TSharedPtr<FJsonObject> LinkObj = MakeShared<FJsonObject>();
				LinkObj->SetObjectField(TEXT("a"), AObj);
				LinkObj->SetObjectField(TEXT("b"), BObj);
				LinksArray.Add(MakeShared<FJsonValueObject>(LinkObj));
			}
		}
	}

	TSharedPtr<FJsonObject> ResultObj = MakeShared<FJsonObject>();
	ResultObj->SetStringField(TEXT("graph_path"), GraphPath);
	ResultObj->SetNumberField(TEXT("link_count"), LinksArray.Num());
	ResultObj->SetArrayField(TEXT("links"), LinksArray);
	return FUnrealMCPCommonUtils::CreateSuccessResponse(ResultObj);
}

// ─────────────────── HandleConnectPins ───────────────────

FJsonObjectParameter UMCPEdGraphTools::HandleConnectPins(const FJsonObjectParameter& Params)
{
	FString GraphPath;
	if (!Params->TryGetStringField(TEXT("graph_path"), GraphPath))
	{
		return FUnrealMCPCommonUtils::CreateErrorResponse(TEXT("Missing 'graph_path' parameter"));
	}

	FString FromNodeGuid, FromPinName, ToNodeGuid, ToPinName;
	if (!Params->TryGetStringField(TEXT("from_node_guid"), FromNodeGuid))
	{
		return FUnrealMCPCommonUtils::CreateErrorResponse(TEXT("Missing 'from_node_guid' parameter"));
	}
	if (!Params->TryGetStringField(TEXT("from_pin"), FromPinName))
	{
		return FUnrealMCPCommonUtils::CreateErrorResponse(TEXT("Missing 'from_pin' parameter"));
	}
	if (!Params->TryGetStringField(TEXT("to_node_guid"), ToNodeGuid))
	{
		return FUnrealMCPCommonUtils::CreateErrorResponse(TEXT("Missing 'to_node_guid' parameter"));
	}
	if (!Params->TryGetStringField(TEXT("to_pin"), ToPinName))
	{
		return FUnrealMCPCommonUtils::CreateErrorResponse(TEXT("Missing 'to_pin' parameter"));
	}

	FString AutoSavePath;
	Params->TryGetStringField(TEXT("auto_save_asset_path"), AutoSavePath);

	UEdGraph* Graph = LoadObject<UEdGraph>(nullptr, *GraphPath);
	if (!Graph)
	{
		return FUnrealMCPCommonUtils::CreateErrorResponse(FString::Printf(TEXT("Graph not found: %s"), *GraphPath));
	}

	UEdGraphNode* FromNode = FindNodeInGraph(Graph, FromNodeGuid, TEXT(""), TEXT(""));
	UEdGraphNode* ToNode = FindNodeInGraph(Graph, ToNodeGuid, TEXT(""), TEXT(""));
	if (!FromNode || !ToNode)
	{
		return FUnrealMCPCommonUtils::CreateErrorResponse(TEXT("From/To node not found"));
	}

	UEdGraphPin* FromPin = FindPinOnNode(FromNode, FromPinName);
	UEdGraphPin* ToPin = FindPinOnNode(ToNode, ToPinName);
	if (!FromPin || !ToPin)
	{
		return FUnrealMCPCommonUtils::CreateErrorResponse(TEXT("From/To pin not found"));
	}

	bool bOk = false;

	// Try Schema first
	const UEdGraphSchema* Schema = Graph->GetSchema();
	if (Schema)
	{
		bOk = Schema->TryCreateConnection(FromPin, ToPin);
	}

	if (!bOk)
	{
		// Fallback: direct link
		FromPin->MakeLinkTo(ToPin);
		bOk = FromPin->LinkedTo.Contains(ToPin);
	}

	if (!AutoSavePath.IsEmpty())
	{
		SaveAssetIfNeeded(AutoSavePath);
	}

	TSharedPtr<FJsonObject> ResultObj = MakeShared<FJsonObject>();
	ResultObj->SetBoolField(TEXT("connected"), bOk);
	return bOk
		? FUnrealMCPCommonUtils::CreateSuccessResponse(ResultObj)
		: FUnrealMCPCommonUtils::CreateErrorResponse(TEXT("Failed to connect pins"));
}

// ─────────────────── HandleDisconnectPin ───────────────────

FJsonObjectParameter UMCPEdGraphTools::HandleDisconnectPin(const FJsonObjectParameter& Params)
{
	FString GraphPath;
	if (!Params->TryGetStringField(TEXT("graph_path"), GraphPath))
	{
		return FUnrealMCPCommonUtils::CreateErrorResponse(TEXT("Missing 'graph_path' parameter"));
	}

	FString NodeGuid, PinName;
	if (!Params->TryGetStringField(TEXT("node_guid"), NodeGuid))
	{
		return FUnrealMCPCommonUtils::CreateErrorResponse(TEXT("Missing 'node_guid' parameter"));
	}
	if (!Params->TryGetStringField(TEXT("pin_name"), PinName))
	{
		return FUnrealMCPCommonUtils::CreateErrorResponse(TEXT("Missing 'pin_name' parameter"));
	}

	FString AutoSavePath;
	Params->TryGetStringField(TEXT("auto_save_asset_path"), AutoSavePath);

	UEdGraph* Graph = LoadObject<UEdGraph>(nullptr, *GraphPath);
	if (!Graph)
	{
		return FUnrealMCPCommonUtils::CreateErrorResponse(FString::Printf(TEXT("Graph not found: %s"), *GraphPath));
	}

	UEdGraphNode* Node = FindNodeInGraph(Graph, NodeGuid, TEXT(""), TEXT(""));
	if (!Node)
	{
		return FUnrealMCPCommonUtils::CreateErrorResponse(TEXT("Node not found"));
	}

	UEdGraphPin* Pin = FindPinOnNode(Node, PinName);
	if (!Pin)
	{
		return FUnrealMCPCommonUtils::CreateErrorResponse(FString::Printf(TEXT("Pin '%s' not found"), *PinName));
	}

	Graph->Modify();
	int32 BrokenCount = Pin->LinkedTo.Num();
	Pin->BreakAllPinLinks();

	if (!AutoSavePath.IsEmpty())
	{
		SaveAssetIfNeeded(AutoSavePath);
	}

	TSharedPtr<FJsonObject> ResultObj = MakeShared<FJsonObject>();
	ResultObj->SetNumberField(TEXT("broken_link_count"), BrokenCount);
	return FUnrealMCPCommonUtils::CreateSuccessResponse(ResultObj);
}

// ─────────────────── HandleAddCommentNode ───────────────────

FJsonObjectParameter UMCPEdGraphTools::HandleAddCommentNode(const FJsonObjectParameter& Params)
{
	FString GraphPath;
	if (!Params->TryGetStringField(TEXT("graph_path"), GraphPath))
	{
		return FUnrealMCPCommonUtils::CreateErrorResponse(TEXT("Missing 'graph_path' parameter"));
	}

	FString Comment;
	if (!Params->TryGetStringField(TEXT("comment"), Comment))
	{
		return FUnrealMCPCommonUtils::CreateErrorResponse(TEXT("Missing 'comment' parameter"));
	}

	double DPosX = 0, DPosY = 0, DWidth = 400, DHeight = 100;
	Params->TryGetNumberField(TEXT("pos_x"), DPosX);
	Params->TryGetNumberField(TEXT("pos_y"), DPosY);
	Params->TryGetNumberField(TEXT("width"), DWidth);
	Params->TryGetNumberField(TEXT("height"), DHeight);

	FString AutoSavePath;
	Params->TryGetStringField(TEXT("auto_save_asset_path"), AutoSavePath);

	UEdGraph* Graph = LoadObject<UEdGraph>(nullptr, *GraphPath);
	if (!Graph)
	{
		return FUnrealMCPCommonUtils::CreateErrorResponse(FString::Printf(TEXT("Graph not found: %s"), *GraphPath));
	}

	Graph->Modify();

	UEdGraphNode_Comment* CommentNode = NewObject<UEdGraphNode_Comment>(Graph);
	CommentNode->SetFlags(RF_Transactional);
	CommentNode->CreateNewGuid();
	CommentNode->NodeComment = Comment;
	CommentNode->NodePosX = static_cast<int32>(DPosX);
	CommentNode->NodePosY = static_cast<int32>(DPosY);
	CommentNode->NodeWidth = static_cast<int32>(DWidth);
	CommentNode->NodeHeight = static_cast<int32>(DHeight);

	Graph->AddNode(CommentNode, true, false);

	if (!AutoSavePath.IsEmpty())
	{
		SaveAssetIfNeeded(AutoSavePath);
	}

	TSharedPtr<FJsonObject> ResultObj = MakeShared<FJsonObject>();
	ResultObj->SetObjectField(TEXT("node"), SerializeNode(CommentNode, false));
	return FUnrealMCPCommonUtils::CreateSuccessResponse(ResultObj);
}

// ─────────────────── ResolveNodeClass (private) ───────────────────

UClass* UMCPEdGraphTools::ResolveNodeClass(const FString& ClassName)
{
	if (ClassName.IsEmpty()) return nullptr;

	// 1. Full path (e.g. "/Script/BlueprintGraph.K2Node_CallFunction")
	UClass* Cls = LoadClass<UEdGraphNode>(nullptr, *ClassName);
	if (Cls) return Cls;

	// 2. Short name exact match
	Cls = FindFirstObject<UClass>(*ClassName, EFindFirstObjectOptions::NativeFirst);
	if (Cls && Cls->IsChildOf(UEdGraphNode::StaticClass())) return Cls;

	// 3. Try with "U" prefix
	if (!ClassName.StartsWith(TEXT("U")))
	{
		FString WithU = TEXT("U") + ClassName;
		Cls = FindFirstObject<UClass>(*WithU, EFindFirstObjectOptions::NativeFirst);
		if (Cls && Cls->IsChildOf(UEdGraphNode::StaticClass())) return Cls;
	}

	// 4. Search all classes by name suffix match
	const FString Target = ClassName;
	for (TObjectIterator<UClass> It; It; ++It)
	{
		if (It->GetName() == Target && It->IsChildOf(UEdGraphNode::StaticClass()))
		{
			return *It;
		}
	}

	return nullptr;
}

// ─────────────────── HandleAddNode ───────────────────

FJsonObjectParameter UMCPEdGraphTools::HandleAddNode(const FJsonObjectParameter& Params)
{
	FString GraphPath;
	if (!Params->TryGetStringField(TEXT("graph_path"), GraphPath))
	{
		return FUnrealMCPCommonUtils::CreateErrorResponse(TEXT("Missing 'graph_path' parameter"));
	}

	FString NodeClassName;
	if (!Params->TryGetStringField(TEXT("node_class"), NodeClassName))
	{
		return FUnrealMCPCommonUtils::CreateErrorResponse(TEXT("Missing 'node_class' parameter"));
	}

	double DPosX = 0, DPosY = 0;
	Params->TryGetNumberField(TEXT("pos_x"), DPosX);
	Params->TryGetNumberField(TEXT("pos_y"), DPosY);

	const TSharedPtr<FJsonObject>* ImportTextPtr = nullptr;
	Params->TryGetObjectField(TEXT("import_text"), ImportTextPtr);

	const TSharedPtr<FJsonObject>* PinDefaultsPtr = nullptr;
	Params->TryGetObjectField(TEXT("pin_defaults"), PinDefaultsPtr);

	UEdGraph* Graph = LoadObject<UEdGraph>(nullptr, *GraphPath);
	if (!Graph)
	{
		return FUnrealMCPCommonUtils::CreateErrorResponse(FString::Printf(TEXT("Graph not found: %s"), *GraphPath));
	}

	UClass* NodeClass = ResolveNodeClass(NodeClassName);
	if (!NodeClass)
	{
		return FUnrealMCPCommonUtils::CreateErrorResponse(FString::Printf(TEXT("Node class not found: %s"), *NodeClassName));
	}

	Graph->Modify();

	UEdGraphNode* Node = NewObject<UEdGraphNode>(Graph, NodeClass);
	Node->SetFlags(RF_Transactional);
	Node->CreateNewGuid();
	Node->NodePosX = static_cast<int32>(DPosX);
	Node->NodePosY = static_cast<int32>(DPosY);

	// Apply ImportText properties BEFORE AllocateDefaultPins
	TSharedPtr<FJsonObject> ImportErrors = MakeShared<FJsonObject>();
	if (ImportTextPtr && ImportTextPtr->IsValid())
	{
		for (const auto& Pair : (*ImportTextPtr)->Values)
		{
			FString TextValue;
			if (!Pair.Value->TryGetString(TextValue))
			{
				ImportErrors->SetStringField(Pair.Key, TEXT("Value is not a string"));
				continue;
			}

			FProperty* Prop = NodeClass->FindPropertyByName(*Pair.Key);
			if (!Prop)
			{
				// Also try in parent classes
				Prop = FindFProperty<FProperty>(NodeClass, *Pair.Key);
			}
			if (!Prop)
			{
				ImportErrors->SetStringField(Pair.Key, TEXT("Property not found"));
				continue;
			}

			void* ValuePtr = Prop->ContainerPtrToValuePtr<void>(Node);
			const TCHAR* Result = Prop->ImportText_Direct(*TextValue, ValuePtr, Node, PPF_None);
			if (!Result)
			{
				ImportErrors->SetStringField(Pair.Key, FString::Printf(TEXT("ImportText failed for value: %s"), *TextValue));
			}
		}
	}

	Node->PostPlacedNewNode();
	Node->AllocateDefaultPins();

	// Apply pin defaults AFTER AllocateDefaultPins
	TSharedPtr<FJsonObject> PinErrors = MakeShared<FJsonObject>();
	if (PinDefaultsPtr && PinDefaultsPtr->IsValid())
	{
		const UEdGraphSchema* Schema = Graph->GetSchema();
		for (const auto& Pair : (*PinDefaultsPtr)->Values)
		{
			FString DefaultValue;
			if (!Pair.Value->TryGetString(DefaultValue))
			{
				PinErrors->SetStringField(Pair.Key, TEXT("Value is not a string"));
				continue;
			}

			UEdGraphPin* Pin = FindPinOnNode(Node, Pair.Key);
			if (!Pin)
			{
				PinErrors->SetStringField(Pair.Key, TEXT("Pin not found"));
				continue;
			}

			if (Schema)
			{
				Schema->TrySetDefaultValue(*Pin, DefaultValue);
			}
			else
			{
				Pin->DefaultValue = DefaultValue;
			}
		}
	}

	Graph->AddNode(Node, true, false);

	TSharedPtr<FJsonObject> ResultObj = MakeShared<FJsonObject>();
	ResultObj->SetObjectField(TEXT("node"), SerializeNode(Node, true));

	if (ImportErrors->Values.Num() > 0)
	{
		ResultObj->SetObjectField(TEXT("import_errors"), ImportErrors);
	}
	if (PinErrors->Values.Num() > 0)
	{
		ResultObj->SetObjectField(TEXT("pin_errors"), PinErrors);
	}

	return FUnrealMCPCommonUtils::CreateSuccessResponse(ResultObj);
}

// ─────────────────── HandleSetPinDefaultValue ───────────────────

FJsonObjectParameter UMCPEdGraphTools::HandleSetPinDefaultValue(const FJsonObjectParameter& Params)
{
	FString GraphPath;
	if (!Params->TryGetStringField(TEXT("graph_path"), GraphPath))
	{
		return FUnrealMCPCommonUtils::CreateErrorResponse(TEXT("Missing 'graph_path' parameter"));
	}

	FString NodeGuid;
	if (!Params->TryGetStringField(TEXT("node_guid"), NodeGuid))
	{
		return FUnrealMCPCommonUtils::CreateErrorResponse(TEXT("Missing 'node_guid' parameter"));
	}

	FString PinName;
	if (!Params->TryGetStringField(TEXT("pin_name"), PinName))
	{
		return FUnrealMCPCommonUtils::CreateErrorResponse(TEXT("Missing 'pin_name' parameter"));
	}

	FString DefaultValue;
	Params->TryGetStringField(TEXT("default_value"), DefaultValue);

	FString DefaultObjectPath;
	Params->TryGetStringField(TEXT("default_object"), DefaultObjectPath);

	FString PinDirection;
	Params->TryGetStringField(TEXT("pin_direction"), PinDirection);

	UEdGraph* Graph = LoadObject<UEdGraph>(nullptr, *GraphPath);
	if (!Graph)
	{
		return FUnrealMCPCommonUtils::CreateErrorResponse(FString::Printf(TEXT("Graph not found: %s"), *GraphPath));
	}

	UEdGraphNode* Node = FindNodeInGraph(Graph, NodeGuid, TEXT(""), TEXT(""));
	if (!Node)
	{
		return FUnrealMCPCommonUtils::CreateErrorResponse(TEXT("Node not found"));
	}

	UEdGraphPin* Pin = FindPinOnNode(Node, PinName, PinDirection);
	if (!Pin)
	{
		return FUnrealMCPCommonUtils::CreateErrorResponse(FString::Printf(TEXT("Pin '%s' not found"), *PinName));
	}

	const UEdGraphSchema* Schema = Graph->GetSchema();
	if (Schema)
	{
		Schema->TrySetDefaultValue(*Pin, DefaultValue);
	}
	else
	{
		Pin->DefaultValue = DefaultValue;
	}

	if (!DefaultObjectPath.IsEmpty())
	{
		UObject* DefaultObj = LoadObject<UObject>(nullptr, *DefaultObjectPath);
		if (DefaultObj)
		{
			Pin->DefaultObject = DefaultObj;
		}
	}

	TSharedPtr<FJsonObject> ResultObj = MakeShared<FJsonObject>();
	ResultObj->SetObjectField(TEXT("pin"), SerializePin(Pin));
	return FUnrealMCPCommonUtils::CreateSuccessResponse(ResultObj);
}

// ─────────────────── HandleCompileAsset ───────────────────

FJsonObjectParameter UMCPEdGraphTools::HandleCompileAsset(const FJsonObjectParameter& Params)
{
	FString AssetPath;
	if (!Params->TryGetStringField(TEXT("asset_path"), AssetPath))
	{
		return FUnrealMCPCommonUtils::CreateErrorResponse(TEXT("Missing 'asset_path' parameter"));
	}

	UObject* Asset = LoadObject<UObject>(nullptr, *AssetPath);
	if (!Asset)
	{
		Asset = UEditorAssetLibrary::LoadAsset(AssetPath);
	}
	if (!Asset)
	{
		return FUnrealMCPCommonUtils::CreateErrorResponse(FString::Printf(TEXT("Asset not found: %s"), *AssetPath));
	}

	UBlueprint* Blueprint = Cast<UBlueprint>(Asset);
	if (!Blueprint)
	{
		return FUnrealMCPCommonUtils::CreateErrorResponse(FString::Printf(TEXT("Asset is not a Blueprint: %s (%s)"), *AssetPath, *Asset->GetClass()->GetName()));
	}

	FKismetEditorUtilities::CompileBlueprint(Blueprint);

	FString StatusStr;
	bool bHasError = false;
	switch (Blueprint->Status)
	{
	case BS_UpToDate:
		StatusStr = TEXT("success");
		break;
	case BS_UpToDateWithWarnings:
		StatusStr = TEXT("warning");
		break;
	case BS_Error:
		StatusStr = TEXT("error");
		bHasError = true;
		break;
	case BS_Dirty:
		StatusStr = TEXT("dirty");
		break;
	default:
		StatusStr = TEXT("unknown");
		break;
	}

	TArray<TSharedPtr<FJsonValue>> MessagesArray;

	// Collect compile messages from the Blueprint's MessageLog
	if (Blueprint->CurrentMessageLog)
	{
		for (const TSharedRef<FTokenizedMessage>& Msg : Blueprint->CurrentMessageLog->Messages)
		{
			TSharedPtr<FJsonObject> MsgObj = MakeShared<FJsonObject>();

			switch (Msg->GetSeverity())
			{
			case EMessageSeverity::Error:
				MsgObj->SetStringField(TEXT("severity"), TEXT("error"));
				break;
			case EMessageSeverity::Warning:
			case EMessageSeverity::PerformanceWarning:
				MsgObj->SetStringField(TEXT("severity"), TEXT("warning"));
				break;
			default:
				MsgObj->SetStringField(TEXT("severity"), TEXT("info"));
				break;
			}

			MsgObj->SetStringField(TEXT("message"), Msg->ToText().ToString());
			MessagesArray.Add(MakeShared<FJsonValueObject>(MsgObj));
		}
	}

	TSharedPtr<FJsonObject> ResultObj = MakeShared<FJsonObject>();
	ResultObj->SetStringField(TEXT("asset_path"), AssetPath);
	ResultObj->SetStringField(TEXT("status"), StatusStr);
	ResultObj->SetBoolField(TEXT("has_error"), bHasError);
	ResultObj->SetArrayField(TEXT("messages"), MessagesArray);
	return FUnrealMCPCommonUtils::CreateSuccessResponse(ResultObj);
}

// ─────────────────── HandleCreateGraph ───────────────────

FJsonObjectParameter UMCPEdGraphTools::HandleCreateGraph(const FJsonObjectParameter& Params)
{
	FString AssetPath;
	if (!Params->TryGetStringField(TEXT("asset_path"), AssetPath))
	{
		return FUnrealMCPCommonUtils::CreateErrorResponse(TEXT("Missing 'asset_path' parameter"));
	}

	FString GraphName;
	if (!Params->TryGetStringField(TEXT("graph_name"), GraphName))
	{
		return FUnrealMCPCommonUtils::CreateErrorResponse(TEXT("Missing 'graph_name' parameter"));
	}

	FString GraphType = TEXT("function");
	Params->TryGetStringField(TEXT("graph_type"), GraphType);

	UObject* Asset = LoadObject<UObject>(nullptr, *AssetPath);
	if (!Asset) Asset = UEditorAssetLibrary::LoadAsset(AssetPath);
	if (!Asset)
	{
		return FUnrealMCPCommonUtils::CreateErrorResponse(FString::Printf(TEXT("Asset not found: %s"), *AssetPath));
	}

	UBlueprint* Blueprint = Cast<UBlueprint>(Asset);
	if (!Blueprint)
	{
		return FUnrealMCPCommonUtils::CreateErrorResponse(TEXT("Asset is not a Blueprint"));
	}

	UEdGraph* NewGraph = nullptr;

	if (GraphType.Equals(TEXT("function"), ESearchCase::IgnoreCase))
	{
		NewGraph = FBlueprintEditorUtils::CreateNewGraph(Blueprint, FName(*GraphName), UEdGraph::StaticClass(), UEdGraphSchema_K2::StaticClass());
		if (NewGraph)
		{
			FBlueprintEditorUtils::AddFunctionGraph<UClass>(Blueprint, NewGraph, false, nullptr);
		}
	}
	else if (GraphType.Equals(TEXT("macro"), ESearchCase::IgnoreCase))
	{
		NewGraph = FBlueprintEditorUtils::CreateNewGraph(Blueprint, FName(*GraphName), UEdGraph::StaticClass(), UEdGraphSchema_K2::StaticClass());
		if (NewGraph)
		{
			FBlueprintEditorUtils::AddMacroGraph(Blueprint, NewGraph, false, nullptr);
		}
	}
	else
	{
		return FUnrealMCPCommonUtils::CreateErrorResponse(FString::Printf(TEXT("Unknown graph_type: %s (supported: function, macro)"), *GraphType));
	}

	if (!NewGraph)
	{
		return FUnrealMCPCommonUtils::CreateErrorResponse(TEXT("Failed to create graph"));
	}

	Blueprint->MarkPackageDirty();

	TSharedPtr<FJsonObject> ResultObj = MakeShared<FJsonObject>();
	ResultObj->SetStringField(TEXT("graph_name"), NewGraph->GetName());
	ResultObj->SetStringField(TEXT("graph_path"), NewGraph->GetPathName());
	ResultObj->SetStringField(TEXT("graph_class"), NewGraph->GetClass()->GetName());
	ResultObj->SetNumberField(TEXT("node_count"), NewGraph->Nodes.Num());
	return FUnrealMCPCommonUtils::CreateSuccessResponse(ResultObj);
}

// ─────────────────── HandleDeleteGraph ───────────────────

FJsonObjectParameter UMCPEdGraphTools::HandleDeleteGraph(const FJsonObjectParameter& Params)
{
	FString AssetPath;
	if (!Params->TryGetStringField(TEXT("asset_path"), AssetPath))
	{
		return FUnrealMCPCommonUtils::CreateErrorResponse(TEXT("Missing 'asset_path' parameter"));
	}

	FString GraphName, GraphPath;
	Params->TryGetStringField(TEXT("graph_name"), GraphName);
	Params->TryGetStringField(TEXT("graph_path"), GraphPath);

	if (GraphName.IsEmpty() && GraphPath.IsEmpty())
	{
		return FUnrealMCPCommonUtils::CreateErrorResponse(TEXT("Provide 'graph_name' or 'graph_path'"));
	}

	UObject* Asset = LoadObject<UObject>(nullptr, *AssetPath);
	if (!Asset) Asset = UEditorAssetLibrary::LoadAsset(AssetPath);
	if (!Asset)
	{
		return FUnrealMCPCommonUtils::CreateErrorResponse(FString::Printf(TEXT("Asset not found: %s"), *AssetPath));
	}

	UBlueprint* Blueprint = Cast<UBlueprint>(Asset);
	if (!Blueprint)
	{
		return FUnrealMCPCommonUtils::CreateErrorResponse(TEXT("Asset is not a Blueprint"));
	}

	UEdGraph* TargetGraph = nullptr;

	if (!GraphPath.IsEmpty())
	{
		TargetGraph = LoadObject<UEdGraph>(nullptr, *GraphPath);
	}

	if (!TargetGraph && !GraphName.IsEmpty())
	{
		auto FindByName = [&GraphName](const auto& Arr) -> UEdGraph* {
			for (UEdGraph* G : Arr)
			{
				if (G && G->GetName() == GraphName) return G;
			}
			return nullptr;
		};

		TargetGraph = FindByName(Blueprint->FunctionGraphs);
		if (!TargetGraph) TargetGraph = FindByName(Blueprint->MacroGraphs);
		if (!TargetGraph) TargetGraph = FindByName(Blueprint->UbergraphPages);
		if (!TargetGraph) TargetGraph = FindByName(Blueprint->EventGraphs);
	}

	if (!TargetGraph)
	{
		return FUnrealMCPCommonUtils::CreateErrorResponse(TEXT("Graph not found"));
	}

	FString RemovedName = TargetGraph->GetName();
	FBlueprintEditorUtils::RemoveGraph(Blueprint, TargetGraph);
	Blueprint->MarkPackageDirty();

	TSharedPtr<FJsonObject> ResultObj = MakeShared<FJsonObject>();
	ResultObj->SetStringField(TEXT("removed_graph"), RemovedName);
	return FUnrealMCPCommonUtils::CreateSuccessResponse(ResultObj);
}

// ─────────────────── HandleGetAssetInfo ───────────────────

FJsonObjectParameter UMCPEdGraphTools::HandleGetAssetInfo(const FJsonObjectParameter& Params)
{
	FString AssetPath;
	if (!Params->TryGetStringField(TEXT("asset_path"), AssetPath))
	{
		return FUnrealMCPCommonUtils::CreateErrorResponse(TEXT("Missing 'asset_path' parameter"));
	}

	UObject* Asset = LoadObject<UObject>(nullptr, *AssetPath);
	if (!Asset) Asset = UEditorAssetLibrary::LoadAsset(AssetPath);
	if (!Asset)
	{
		return FUnrealMCPCommonUtils::CreateErrorResponse(FString::Printf(TEXT("Asset not found: %s"), *AssetPath));
	}

	TSharedPtr<FJsonObject> ResultObj = MakeShared<FJsonObject>();
	ResultObj->SetStringField(TEXT("asset_path"), AssetPath);
	ResultObj->SetStringField(TEXT("asset_class"), Asset->GetClass()->GetName());

	UBlueprint* Blueprint = Cast<UBlueprint>(Asset);
	if (!Blueprint)
	{
		// Non-blueprint asset: just return basic info + graphs
		TArray<TSharedPtr<FJsonValue>> GraphsArray;
		TArray<UObject*> SubObjects;
		GetObjectsWithOuter(Asset, SubObjects, false);
		for (UObject* Obj : SubObjects)
		{
			UEdGraph* G = Cast<UEdGraph>(Obj);
			if (!G) continue;
			TSharedPtr<FJsonObject> GO = MakeShared<FJsonObject>();
			GO->SetStringField(TEXT("name"), G->GetName());
			GO->SetStringField(TEXT("path"), G->GetPathName());
			GO->SetStringField(TEXT("class"), G->GetClass()->GetName());
			GO->SetNumberField(TEXT("node_count"), G->Nodes.Num());
			GraphsArray.Add(MakeShared<FJsonValueObject>(GO));
		}
		ResultObj->SetArrayField(TEXT("graphs"), GraphsArray);
		return FUnrealMCPCommonUtils::CreateSuccessResponse(ResultObj);
	}

	// Parent class
	if (Blueprint->ParentClass)
	{
		ResultObj->SetStringField(TEXT("parent_class"), Blueprint->ParentClass->GetName());
		ResultObj->SetStringField(TEXT("parent_class_path"), Blueprint->ParentClass->GetPathName());
	}

	// Blueprint type
	ResultObj->SetStringField(TEXT("blueprint_type"), 
		Blueprint->BlueprintType == BPTYPE_Normal ? TEXT("Normal") :
		Blueprint->BlueprintType == BPTYPE_MacroLibrary ? TEXT("MacroLibrary") :
		Blueprint->BlueprintType == BPTYPE_Interface ? TEXT("Interface") :
		Blueprint->BlueprintType == BPTYPE_FunctionLibrary ? TEXT("FunctionLibrary") :
		TEXT("Other"));

	// Variables
	TArray<TSharedPtr<FJsonValue>> VarsArray;
	for (const FBPVariableDescription& Var : Blueprint->NewVariables)
	{
		TSharedPtr<FJsonObject> VarObj = MakeShared<FJsonObject>();
		VarObj->SetStringField(TEXT("name"), Var.VarName.ToString());
		VarObj->SetStringField(TEXT("type"), Var.VarType.PinCategory.ToString());
		if (Var.VarType.PinSubCategoryObject.IsValid())
		{
			VarObj->SetStringField(TEXT("sub_type"), Var.VarType.PinSubCategoryObject->GetName());
		}
		VarObj->SetStringField(TEXT("category"), Var.Category.ToString());
		VarObj->SetBoolField(TEXT("is_instance_editable"), Var.PropertyFlags & CPF_Edit ? true : false);
		VarObj->SetBoolField(TEXT("is_array"), Var.VarType.IsArray());

		// Export default value text
		if (!Var.DefaultValue.IsEmpty())
		{
			VarObj->SetStringField(TEXT("default_value"), Var.DefaultValue);
		}

		VarsArray.Add(MakeShared<FJsonValueObject>(VarObj));
	}
	ResultObj->SetArrayField(TEXT("variables"), VarsArray);

	// Functions (from FunctionGraphs)
	TArray<TSharedPtr<FJsonValue>> FuncsArray;
	for (UEdGraph* FuncGraph : Blueprint->FunctionGraphs)
	{
		if (!FuncGraph) continue;
		TSharedPtr<FJsonObject> FuncObj = MakeShared<FJsonObject>();
		FuncObj->SetStringField(TEXT("name"), FuncGraph->GetName());
		FuncObj->SetStringField(TEXT("graph_path"), FuncGraph->GetPathName());
		FuncObj->SetNumberField(TEXT("node_count"), FuncGraph->Nodes.Num());

		// Try to get function flags from the generated class
		if (Blueprint->GeneratedClass)
		{
			UFunction* Func = Blueprint->GeneratedClass->FindFunctionByName(FName(*FuncGraph->GetName()));
			if (Func)
			{
				FuncObj->SetBoolField(TEXT("is_pure"), Func->HasAnyFunctionFlags(FUNC_BlueprintPure));
				FuncObj->SetBoolField(TEXT("is_static"), Func->HasAnyFunctionFlags(FUNC_Static));
				FuncObj->SetStringField(TEXT("access"),
					Func->HasAnyFunctionFlags(FUNC_Public) ? TEXT("Public") :
					Func->HasAnyFunctionFlags(FUNC_Protected) ? TEXT("Protected") :
					TEXT("Private"));
			}
		}

		FuncsArray.Add(MakeShared<FJsonValueObject>(FuncObj));
	}
	ResultObj->SetArrayField(TEXT("functions"), FuncsArray);

	// Macros
	TArray<TSharedPtr<FJsonValue>> MacrosArray;
	for (UEdGraph* MacroGraph : Blueprint->MacroGraphs)
	{
		if (!MacroGraph) continue;
		TSharedPtr<FJsonObject> MacroObj = MakeShared<FJsonObject>();
		MacroObj->SetStringField(TEXT("name"), MacroGraph->GetName());
		MacroObj->SetStringField(TEXT("graph_path"), MacroGraph->GetPathName());
		MacroObj->SetNumberField(TEXT("node_count"), MacroGraph->Nodes.Num());
		MacrosArray.Add(MakeShared<FJsonValueObject>(MacroObj));
	}
	if (MacrosArray.Num() > 0)
	{
		ResultObj->SetArrayField(TEXT("macros"), MacrosArray);
	}

	// Interfaces
	TArray<TSharedPtr<FJsonValue>> InterfacesArray;
	for (const FBPInterfaceDescription& Iface : Blueprint->ImplementedInterfaces)
	{
		if (!Iface.Interface) continue;
		TSharedPtr<FJsonObject> IfObj = MakeShared<FJsonObject>();
		IfObj->SetStringField(TEXT("name"), Iface.Interface->GetName());
		IfObj->SetStringField(TEXT("path"), Iface.Interface->GetPathName());
		InterfacesArray.Add(MakeShared<FJsonValueObject>(IfObj));
	}
	if (InterfacesArray.Num() > 0)
	{
		ResultObj->SetArrayField(TEXT("interfaces"), InterfacesArray);
	}

	// Components (SCS)
	if (Blueprint->SimpleConstructionScript)
	{
		TArray<TSharedPtr<FJsonValue>> CompsArray;
		TArray<USCS_Node*> AllNodes = Blueprint->SimpleConstructionScript->GetAllNodes();
		for (USCS_Node* SCSNode : AllNodes)
		{
			if (!SCSNode) continue;
			TSharedPtr<FJsonObject> CompObj = MakeShared<FJsonObject>();
			CompObj->SetStringField(TEXT("name"), SCSNode->GetVariableName().ToString());
			CompObj->SetStringField(TEXT("class"), SCSNode->ComponentClass ? SCSNode->ComponentClass->GetName() : TEXT(""));
			if (SCSNode->ParentComponentOrVariableName != NAME_None)
			{
				CompObj->SetStringField(TEXT("parent"), SCSNode->ParentComponentOrVariableName.ToString());
			}
			CompsArray.Add(MakeShared<FJsonValueObject>(CompObj));
		}
		ResultObj->SetArrayField(TEXT("components"), CompsArray);
	}

	// Graphs overview
	TArray<TSharedPtr<FJsonValue>> GraphsArray;
	auto AddGraphs = [&](const auto& Arr, const FString& Category)
	{
		for (UEdGraph* G : Arr)
		{
			if (!G) continue;
			TSharedPtr<FJsonObject> GO = MakeShared<FJsonObject>();
			GO->SetStringField(TEXT("name"), G->GetName());
			GO->SetStringField(TEXT("path"), G->GetPathName());
			GO->SetStringField(TEXT("class"), G->GetClass()->GetName());
			GO->SetStringField(TEXT("category"), Category);
			GO->SetNumberField(TEXT("node_count"), G->Nodes.Num());
			GraphsArray.Add(MakeShared<FJsonValueObject>(GO));
		}
	};
	AddGraphs(Blueprint->UbergraphPages, TEXT("UbergraphPages"));
	AddGraphs(Blueprint->FunctionGraphs, TEXT("FunctionGraphs"));
	AddGraphs(Blueprint->MacroGraphs, TEXT("MacroGraphs"));
	AddGraphs(Blueprint->DelegateSignatureGraphs, TEXT("DelegateSignatureGraphs"));
	AddGraphs(Blueprint->EventGraphs, TEXT("EventGraphs"));

	// Also scan sub-objects for any other graphs (AnimGraph, etc.)
	TArray<UObject*> SubObjects;
	GetObjectsWithOuter(Asset, SubObjects, false);
	TSet<FString> SeenPaths;
	for (const auto& GA : GraphsArray)
	{
		SeenPaths.Add(GA->AsObject()->GetStringField(TEXT("path")));
	}
	for (UObject* Obj : SubObjects)
	{
		UEdGraph* G = Cast<UEdGraph>(Obj);
		if (!G) continue;
		FString GPath = G->GetPathName();
		if (SeenPaths.Contains(GPath)) continue;
		TSharedPtr<FJsonObject> GO = MakeShared<FJsonObject>();
		GO->SetStringField(TEXT("name"), G->GetName());
		GO->SetStringField(TEXT("path"), GPath);
		GO->SetStringField(TEXT("class"), G->GetClass()->GetName());
		GO->SetStringField(TEXT("category"), TEXT("Other"));
		GO->SetNumberField(TEXT("node_count"), G->Nodes.Num());
		GraphsArray.Add(MakeShared<FJsonValueObject>(GO));
	}
	ResultObj->SetArrayField(TEXT("graphs"), GraphsArray);

	return FUnrealMCPCommonUtils::CreateSuccessResponse(ResultObj);
}
